### ISSUE TITLE
[JOSS Review] Paper comments

### ISSUE THREAD

**Issue by jasondegraw** [wouterpeere/GHEtool#11]
@wouterpeere I'm the other reviewer of the JOSS paper, and here is some feedback on the paper. There some fairly minor things in two areas.

- Statement of Need: The sentence [here](https://github.com/wouterpeere/GHEtool/blob/9229ddd1bef1a68741bffe8cae3860e216792409/JOSS/Paper.md?plain=1#L41) "This sector should decarbonize to reach the climate goals in 2050." is a command because of the way "should" is used and the use of 2050 calls for a reference. If there is a desire to keep the specific year of 2050 in the text, there needs to be a reference or further explanation as to what is contemplated by 2050. This can be avoided if this sentence is changed to something like "In order to achieve meaningful climate goals, it is likely that progress toward decarbonization of the building sector is required.", then there's no need for an additional reference and it's no longer a command. The following sentence might also need to be adjusted a bit so that there's agreement as to whether there's a singular "goal" or it's plural "goals"
- References: The reference [here](https://github.com/wouterpeere/GHEtool/blob/9229ddd1bef1a68741bffe8cae3860e216792409/JOSS/Paper.md?plain=1#L66) to the IGSHPA website is a bit confusing when the company has a website at groundloopdesign.com. It would be better to link directly to the company website rather than link to a website that links to the company website.

**Comment by wouterpeere** [comment]
@jasondegraw thanks for the comments!



> * Statement of Need: The sentence [here](https://github.com/wouterpeere/GHEtool/blob/9229ddd1bef1a68741bffe8cae3860e216792409/JOSS/Paper.md?plain=1#L41) "This sector should decarbonize to reach the climate goals in 2050." is a command because of the way "should" is used and the use of 2050 calls for a reference. If there is a desire to keep the specific year of 2050 in the text, there needs to be a reference or further explanation as to what is contemplated by 2050. This can be avoided if this sentence is changed to something like "In order to achieve meaningful climate goals, it is likely that progress toward decarbonization of the building sector is required.", then there's no need for an additional reference and it's no longer a command. The following sentence might also need to be adjusted a bit so that there's agreement as to whether there's a singular "goal" or it's plural "goals"

Thank you for pointing out this nuance. The 2050 is there since these goals are set by the European Commission. I rewrote it this way: "In order to reach the climate goals in 2050, as set by the European Green Deal, the building sector should decarbonise [@greenDeal]." Is this OK for you?



> * References: The reference [here](https://github.com/wouterpeere/GHEtool/blob/9229ddd1bef1a68741bffe8cae3860e216792409/JOSS/Paper.md?plain=1#L66) to the IGSHPA website is a bit confusing when the company has a website at groundloopdesign.com. It would be better to link directly to the company website rather than link to a website that links to the company website.

I used the IGSHPA website since the information I quoted in the paper is coming from that site, where it is more 'hidden' on the company website instead. To make it more clear, I included a second reference to groundloopdesign.com

**Comment by wouterpeere** [comment]
I also removed the JOSS folder. The paper (both .md and .bib) are in the main directory. For some reason, I couldn't get the editorialbot working with the subfolder ...

**Comment by jasondegraw** [comment]
@wouterpeere On the first item, I was not able to find anything on the website that supports using "should". If the statement in the paper is made less imperative, using "make progress toward" or a similar phrases, then the attribution would be legitimate because there's plenty there to support that. It's a pretty big website with a lot of documents, so maybe I'm just not finding it? Is there a specific place where I should be looking?

The additional reference to groundloopdesign.com takes care of the second item.

**Comment by wouterpeere** [comment]
@jasondegraw Perhaps the reference I used was indeed not specific enough, but I found this specific page about buildings: https://ec.europa.eu/commission/presscorner/detail/en/IP_21_6683. The main conclusion is that "It complements the other components of the package adopted in July 2021, setting the vision for achieving a zero-emission building stock by 2050." 

Is it OK if I also refer to this webpage and instead of using 'should decarbonise' I use: "strive towards decarbonisation in order to achieve a zero-emission building stock by 2050."?

**Comment by jasondegraw** [comment]
@wouterpeere Sorry, I missed this response. Thank you for being patient, that would solve this and close this issue.

**Comment by wouterpeere** [comment]
@jasondegraw, no problem. I implemented these changes, and I close this issue.
