### ISSUE TITLE
g-function returns negative values

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#187]
Hi @wouterpeere ,

Is it correct that the g_function return negative values under some configurations?
I have implemented a test to show at leat one example.

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Normally not ...

Can you check it with pygfunction? 

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

GHEtool and pygfunction leading to negative values. The question is: shall GHEtool handle this or pygfunction check its limitations?

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Since we use pygfunction for the gfunction calculation, I think it is something that should be checked there. We do not have any code implemented to calculate gfunctions themselves (only interpolation). Can you create an issue at the github of pygfunction?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

We can avoid this error in GHEtool by increasing the "linear_threshold" to for example 24*3600 in general or we implement a check and then increase the threshold. What do you think?

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Increasing this threshold to 24 hours, makes me worry a little bit for sizing with hourly resolution. These first hours make a lot of difference and I'm curious to know is this changes something ...

Do you know?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi  @wouterpeere ,

I do not think that this is going to be an issue for the hourly sizing method since we ask py-g-function to ask the same values for both methods.

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Perhaps not, indeed. I will take a look at this.
Can you figure out why the GitHub tests keep crashing for some reason? It is something I cannot reproduce locally ...

Best,
Wouter

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I also can not reproduce this locally. I have changed the python version to 3.10. This seems to work for some cases. I have no idea why it is crashing.

Best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I took a look at this and implemented the 24 hours linear threshold by default, but this has an extreme effect on the sizing of all the methods we have so far. Since the temperatures are mostly influenced by the peak power, which is multiplied with a gfunction mostly at times smaller than 24*3600s, it influence all the results significantly.

I don't think implementing this as a default is hence a good idea, but also, I do not know if it is to be trusted after all to be honest ...

**Comment by tblanke** [comment]
Hi @wouterpeere 

what do you think about implementing a check for this negative values and if there are some, then perform a new caclulation? I have implemented this new approach.

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I did some more tweaking to optimize your code, however, there's something I do not understand from this approach (and from the discussion over on pygfunction).

What we see in the example you created is that after a certain time threshold, there are random negative gfunctions, but not all of them. Next, we redo the calculation with a linear threshold (which, as I understood it correctly, influences gfunctions below a certain threshold). Afterwards, we combine both the 'original' gfunctions and the new ones, but we use the data with the high linear threshold for the later values where we use the gfunctions without the linear threshold for the first time steps.

I see that it works, but I honestly don't feel comfortable with this, since I don't get why the gfunction values should be different at long timesteps when using a linear threshold ...

**Comment by wouterpeere** [comment]
Hi @tblanke 

I implemented the cylindrical borehole correction as proposed by Massimo.

Best,
@wouterpeere
